export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_OUT = 'SIGN_OUT';

export const CREATE_QUESTION = 'CREATE_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const LOAD_BOOK = 'LOAD_BOOK';

export const SEARCH_QUESTION_ANY = 'SEARCH_QUESTION_ANY';
export const SEARCH_PARAMETERS = 'SEARCH_PARAMETERS';

export const SEARCH_QUESTION_FOR_EXAM = 'SEARCH_QUESTION_FOR_EXAM';
export const CREATE_SOFT_EXAM ='CREATE_SOFT_EXAM';
export const SHOW_EXAM_SEARCH = 'SHOW_EXAM_SEARCH';
export const ADD_QUESTION_TO_EXAM = 'ADD_QUESTION_TO_EXAM';
export const REMOVE_EXAM = 'REMOVE_EXAM';
export const REMOVE_EXAM_ERRORMSG = 'REMOVE_EXAM_ERRORMSG';
export const CREATE_EXAM = 'CREATE_EXAM';
export const LOAD_EXAMS = 'LOAD_EXAMS';

export const BANK_SNACKBAR = 'BANK_SNACKBAR';