export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_OUT = 'SIGN_OUT';

export const CREATE_QUESTION = 'CREATE_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const LOAD_BOOK = 'LOAD_BOOK';

export const SEARCH_QUESTION_TYPE = 'SEARCH_QUESTION_TYPE';
export const SEARCH_QUESTION_LEVEL = 'SEARCH_QUESTION_LEVEL';
export const SEARCH_QUESTION_CATEGORY = 'SEARCH_QUESTION_CATEGORY';
export const SEARCH_QUESTION_ANY = 'SEARCH_QUESTION_ANY';